name: Feature request
description: 機能追加・改善の提案
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 解決したいこと
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 提案
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: 受け入れ条件
      description: チェックリスト形式で
